Save the server! Fix for Region validation.
intermine/bluegenes pull request #303
Opened 2018-12-06 07:51 UTC by sehgalvibhor

## PR authors: Vibhor S.
### Please describe your PR:
Closes #23 
Disables the button if the user does not follow the syntax for the input. This might be a sweet temporary fix, can be improvised in the near future based on subsequent discussion/review.

## Reviewers: 
## Review checklist: 

 Before merging, confirm the following tasks have been executed

- [x] review a _minified_ build (e.g. `lein prod`, _not_ `lein figwheel`). 

Checked the following pages load results successfully and allow you to proceed to the results or report page:

- [ ] ID resolver + results preview
- [ ] Templates execute and show results
- [ ] Templates allow you to select lists AND type in identifiers
- [ ] Search (dropdown preview version)
- [ ] Search (full results page)
- [ ] Report page loads, including homologues and tools
- [ ] Region search
- [ ] Login and logout works for more than one user (use test user demo@intermine.org pw demo if needed)

This is not an exhaustive list - if you spot something else strange please bring it up!

2018-12-24 11:11 UTC, yochannah requested changes
Hey @sehgalvibhor! Sorry for taking so long to test this one. The code you've implemented works great, but I think it needs a little bit more before we can merge it - my concern is that users who are trying to use the region search might not quite know _why_ the form is disabled, in its current state. It might be easier for them if we provide some feedback - perhaps a polite error message explaining the mandatory format and telling them which line is problematic, if there are multiple lines.

One option to implement this might be custom html5 form validation: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Customized_error_messages but other reasonable implementation methods can be considered as well.

If you want to read more about feedback on errors: https://www.nngroup.com/articles/error-message-guidelines/

2018-12-24 11:11 UTC, yochannah commented on src/cljs/bluegenes/pages/regions/views.cljs
> +  [v regex]
The regex works great! Could we add a docstring here explaining what the regex is checking for, in plain english? You can see an example of a docstring on line 152 below.

2018-12-25 03:36 UTC, sehgalvibhor commented
Got it! I'll make the necessary changes and update the PR.

2019-05-01 11:17 UTC, yochannah commented
Hey @sehgalvibhor! This PR has been around a while; I'm going to close it for now but if you wish to work on it further please feel free to re-open it.

2019-05-01 11:17 UTC, closed without merging